## This is basic continuous integration build for your Quarkus application.

name: Quarkus Native CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@latest
      - name: Build native executable and upload it as an artifact
        uses: edufolly/quarkus-native-build-docker-action@master
        with:
          outputName: myapp-runner
      - name: Upload native executable
        uses: actions/upload-artifact@v1
        with:
          name: native-executable
          path: myapp-runner